services:
  db:
    image: pgvector/pgvector:pg17 
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgres/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      dbnet:
        ipv4_address: 172.12.0.2
    ports:
            - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin 
    ports:
      - 80:80
    networks: 
       dbnet:
         ipv4_address: 172.12.0.3
  
  notebook:
    build:
      context: ./
      dockerfile: jupyter.Dockerfile
    volumes:
      - "./:/home/jovyan/work"
    ports:
      - "8888:8888"
    environment:
      PASSWORD: ${NB_PASSWORD}
    networks:
      dbnet:
        ipv4_address: 172.12.0.4


networks:
  dbnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.12.0.0/16
         gateway: 172.12.0.1
