[package]
name = "triplet_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
strsim = "0.10"
rayon = "1.7"
tokio-postgres = "0.7"
dotenv = "0.15"
tokio = { version = "1.45.1", features = ["full"] }
